version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    links:
      - "server"
  server:
    build:
      dockerfile: ./server/Dockerfile
      context: ./
    volumes:
      - server_node_modules:/app/node_modules:rw
    ports:
      - "9090:9090"
volumes:
  server_node_modules:
  client_node_modules:
