version: "3"
services:
  proxy:
    build: ./proxy
    ports:
      - "8080:8080"
    links:
      - "server"
  server:
    build: ./server
    volumes:
      - ./server/:/go/src/hello-grpc-web/server
    ports:
      - "9090:9090"
  # client:
  #   build: ./client
  #   volumes:
  #     - ./client/src:/client/src
  #     - ./client/dist:/client/dist
  #     - ./client/.cache:/client/.cache
  #   ports:
  #     - "3000:3000"
